language: R
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm
  - data

before_install:
- npm install netlify-cli -g
- mkdir data

install:
- curl -d "j_username=jeff.hammerbacher%40gmail.com&j_password=password" http://software.broadinstitute.org/gsea/j_spring_security_check -c - | curl -b @- -o data/msigdb.xml http://software.broadinstitute.org/gsea/msigdb/download_file.jsp?filePath=/resources/msigdb/6.2/msigdb_v6.2.xml

script:
- Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
- ls -ltrhR _book

after_success:
- netlify deploy --prod --dir _book
