language: R
sudo: false
cache:
  packages: true

before_install:
- npm install netlify-cli -g

script:
- Rscript -e 'options(warn=2); rmarkdown::render_site(encoding = "UTF-8")'
- ls -ltrhR _book

after_success:
- netlify deploy --prod --dir _book
