language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

before_install:
- npm install netlify-cli -g

script:
- Rscript -e 'rmarkdown::render_site(encoding = 'UTF-8')'

after_success:
- netlify deploy --prod --dir _book
